### ISSUE TITLE
Fehlermeldung

### ISSUE THREAD

**Issue by OliverFeld** [iobroker-community-adapters/ioBroker.panasonic-viera#122]
Ich bekomme jede Minute folgende Fehlermeldung im Log:

State "panasonic-viera.0.volume" has no existing object, this might lead to an error in future versions
State "panasonic-viera.0.mute" has no existing object, this might lead to an error in future versions

**Versions:**  
 - Adapter version: 1.0.2
 - JS-Controller version: v15.3.0
 - Iobroker Raspberry Pi 4

**Comment by ChrisDuck87** [comment]
get the same error message.

**Comment by ChrisDuck87** [comment]
updated to Version 2.0 - error solved
