### ISSUE TITLE
Adapter crashes repeatedly

### ISSUE THREAD

**Issue by Smibser** [iobroker-community-adapters/ioBroker.panasonic-viera#166]
**Describe the bug**  
iobroker said that the adapter was stoped due to repeatedly crashing. When the TV is on everything works fine.
As it seems the error occurs as soon as i turn off the TV.

**To Reproduce**  
1. Install adapter
2. Enter TV IP
3. Turn off TV and wait couple hours

**Expected behavior**  
Not crashing :sweat_smile:

**Screenshots & Logfiles**  
<img width="1591" alt="Bildschirmfoto 2022-04-12 um 19 33 13" src="https://user-images.githubusercontent.com/56257499/163022417-44cb67ad-c1a5-49f6-99ca-4cb0c81b7e27.png">

**Versions:**  
 - Adapter version: 2.0.0
 - JS-Controller version: 4.0.21
 - Node version: v14.19.1
 - Operating system: linux

**Comment by Steff42** [comment]
Me too.

Adapter crashed bei mir leider auch mit derselben Fehlermeldung.

Adapterversion: 2.0.0
JS-Controller: 4.0.23
Betriebssystem: Debian 11
Node: 16.16.0
NPM: 8.11.0

Gruß Steffen
