### ISSUE TITLE
Adapter erweitern Panasonic 2018/2019 

### ISSUE THREAD

**Issue by jack99n** [iobroker-community-adapters/ioBroker.panasonic-viera#24]
Ich würde mir auch wünschen den Adapter weiter nutzen zu können leider Funktioniert er mit meinem 2019er Panasonic TV nicht. Vielleicht kann ihn ja jemand erweitern das hier habe ich im Netz schon gefunden. 

https://github.com/florianholzapfel/panasonic-viera/blob/master/README.md

https://github.com/florianholzapfel/panasonic-viera/issues/9

**Comment by jack99n** [comment]
https://github.com/ngws/panasonic-viera/blob/master/panasonic_viera/__init__.py

**Comment by Dome2075** [comment]
Gibt's hierzu was neues?

**Comment by Merexor** [comment]
@Dome2075 leider wohl nicht.
Die 2019 und neuer Geräte brauchen ja eine Authentication.
Leider bin ich nicht soweit so eine Adapter zu ändern aber es gibt für Homebridge auch ein Plugin das die Authentication unterstützt, vielleicht kann man sich da auch etwas abschauen.

[https://github.com/AntonioMeireles/homebridge-vieramatic/issues/57](url)
