### ISSUE TITLE
update required since nodejs 12.x

### ISSUE THREAD

**Issue by UwesSmartHome** [iobroker-community-adapters/ioBroker.panasonic-viera#61]
![image](https://user-images.githubusercontent.com/45943079/108768902-93130080-7558-11eb-95b9-9b4944eacb35.png)

**Comment by ChristianWieck1977** [comment]
schließe mich dem Bedarf zum Update an. Bei mir kommen die selben Fehlermeldungen

**Comment by Steff42** [comment]
Der Fehler kommt bei mir nun auch.
Hängt aber eher mit dem Update des JS-Controllers auf die V3.2.x zusammen.
